// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
CANJaguar* RobotMap::intakeIntakeMotor = NULL;
CANJaguar* RobotMap::chassisChassieFrontRight = NULL;
CANJaguar* RobotMap::chassisChassieFrontLeft = NULL;
CANJaguar* RobotMap::chassisChassieBackRight = NULL;
CANJaguar* RobotMap::chassisChassieBackLeft = NULL;
RobotDrive* RobotMap::chassisRobotDrive = NULL;
CANJaguar* RobotMap::conveyorConveyorMotor = NULL;
CANJaguar* RobotMap::shooterShooterMotor7 = NULL;
CANJaguar* RobotMap::shooterShooterMotor8 = NULL;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
void RobotMap::init() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	LiveWindow* lw = LiveWindow::GetInstance();
	intakeIntakeMotor = new CANJaguar(11);
	
	
	chassisChassieFrontRight = new CANJaguar(4);
	
	
	chassisChassieFrontLeft = new CANJaguar(2);
	
	
	chassisChassieBackRight = new CANJaguar(5);
	
	
	chassisChassieBackLeft = new CANJaguar(3);
	
	
	chassisRobotDrive = new RobotDrive(chassisChassieFrontLeft, chassisChassieBackLeft,
              chassisChassieFrontRight, chassisChassieBackRight);
	
	chassisRobotDrive->SetSafetyEnabled(true);
        chassisRobotDrive->SetExpiration(0.1);
        chassisRobotDrive->SetSensitivity(0.5);
        chassisRobotDrive->SetMaxOutput(1.0);
	conveyorConveyorMotor = new CANJaguar(12);
	
	
	shooterShooterMotor7 = new CANJaguar(7);
	
	
	shooterShooterMotor8 = new CANJaguar(8);
	
	
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
